### ISSUE TITLE
What can be done about the other parts of PL/SQL dev that are not code related ?

### ISSUE THREAD

**Issue by dvdvideo1234** [cepruo/plsql-color-schemes#1]
![image](https://user-images.githubusercontent.com/9112662/109270530-d3070b80-7816-11eb-80d8-40191cf88656.png)

**Comment by cepruo** [comment]
What is it mean by saying other parts?
If (basing on the screens provided) it is meant by UI itself, then it depends on the system (Windows  OS) color scheme and it is impossible to change it via PL/SQL Developer settings itself.
If it is meant by tables, connections, backgrounds, etc., I did not include them intentionally, because (IMHO, of course) it is so individual and it is also very difficult for me to pick up the proper color to make it more readable than the default is.

**Comment by dvdvideo1234** [comment]
The screens selected in red. See how the text area and DB  objects are dark but the rest of the applicstion has lighter colors like the ribbon and other screens parent to pl/sql dev. So yeah. It is the user interface. I amusing windows 10 with dark theme.

Where can i change the second scheme at?

**Comment by cepruo** [comment]
I've made an investigation according to your request. It seems like Windows 10 doesn't have the "old school" color scheme options, where you can select the color of buttons, scrollbars, etc. The accessibility option (where these settings are available) cannot provide full control of color settings and looks very contrast (and pl/sql menu ribbon stays gray). So if you use Windows 10, there is no easy and pretty way to do it. In the old version of Windows (7 and older), you may use the "Window color and appearance" dialog to set up your color settings. But again, this will not give you feeling like Intellij Idea give with her dark themes. See also PL/SQL forum thread about this: [PL/SQL Developer  color theme - enhancement request](https://forums.allroundautomations.com/ubb/ubbthreads.php?ubb=showflat&Number=55634&page=1)

**Comment by LuisFerchx** [comment]
How I can change to original theme (defalut) ?

**Comment by cepruo** [comment]
Answered this in #2 
[How to restore default theme](https://github.com/cepruo/plsql-color-schemes/issues/2#issue-835617644)
